In [1]:
import pandas as pd 
import numpy as np
df=pd.read_csv("Advertising.csv")
df=df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [2]:
X=df.drop("sales",axis=1)
y=df["sales"]

In [3]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [4]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [5]:
#sinama test
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


In [7]:
x_train.head()

TV  radio  newspaper
79   116.0    7.7       23.1
197  177.0    9.3        6.4
38    43.1   26.7       35.1
24    62.3   12.6       18.3
122  224.0    2.4       15.6

In [8]:
y_train.head()

79     11.0
197    12.8
38     10.1
24      9.7
122    11.6
Name: sales, dtype: float64

In [9]:
x_test.head()

TV  radio  newspaper
95   163.3   31.6       52.9
15   195.4   47.7       52.9
30   292.9   28.3       43.2
158   11.7   36.9       45.2
128  220.3   49.0        3.2

In [10]:
y_test.head()

95     16.9
15     22.4
30     21.4
158     7.3
128    24.7
Name: sales, dtype: float64

In [11]:
from sklearn.linear_model import LinearRegression

In [14]:
lm=LinearRegression()
model=lm.fit(x_train,y_train)

In [16]:
import numpy as np
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_train,model.predict(x_train)))

# eğitim

1.644727765644337

In [17]:
np.sqrt(mean_squared_error(y_test,model.predict(x_test)))
        #test 

1.78159966153345

In [18]:
#k-katlı cv

In [19]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(model,x_train,y_train,cv=10,scoring="neg_mean_squared_error")

array([-5.57303426, -2.86235681, -2.06504684, -1.09186983, -1.66159795,
       -2.50694042, -2.92821679, -2.01207197, -7.2250041 , -1.66156243])

In [22]:
-cross_val_score(model,x_train,y_train,cv=10,scoring="neg_mean_squared_error")

array([-5.57303426, -2.86235681, -2.06504684, -1.09186983, -1.66159795,
       -2.50694042, -2.92821679, -2.01207197, -7.2250041 , -1.66156243])

In [23]:
-cross_val_score(model,x_train,y_train,cv=10,scoring="neg_mean_squared_error")

array([5.57303426, 2.86235681, 2.06504684, 1.09186983, 1.66159795,
       2.50694042, 2.92821679, 2.01207197, 7.2250041 , 1.66156243])

In [24]:
#cv rmse
np.sqrt(np.mean(-cross_val_score(model,x_train,y_train,cv=10,scoring="neg_mean_squared_error")))

1.720107595088097